name: Quality and Assurance

on:
  push:
  pull_request:

jobs:
  qa:
    name: Quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions:
          - 8.2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, intl, dom, filter
        env:
          update: true

      - name: Install Composer dependencies
        run: composer install --working-dir=qa/php-cs-fixer

      - name: PHP-CS-Fixer
        run: ./qa/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --using-cache=no --verbose --diff

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-versions:
          - 8.1
          - 8.2
          - 8.3
        symfony-versions:
          - 5.4.*
          - 6.3.*
          - 6.4.*
          - 7.0.*
        dependencies:
          - ''
        include:
          - php-versions: '8.1'
            symfony-versions: '5.4.*'
            dependencies: 'lowest'
        exclude:
          - php-versions: '8.1'
            symfony-versions: '7.0.*'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json
          tools: flex
        env:
          update: true

      - name: Install Composer
        if: "matrix.dependencies == ''"
        run: composer update --no-progress --ansi --prefer-stable
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-versions }}

      - name: Install Lowest Composer dependencies
        if: "matrix.dependencies == 'lowest'"
        run: composer update --no-progress --ansi --prefer-stable --prefer-lowest
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony-versions }}

      - name: Validate composer
        run: composer validate --strict --no-check-lock

      - name: Execute unit tests
        run: ./vendor/bin/simple-phpunit
